version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    restart: on-failure
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_USER: usuario
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: on-failure
    container_name: adminer
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: on-failure
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8002:8002"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    # depends_on:
    #   db:
    #     - redis
    #     condition: 
    #       - service_healthy
    environment:
      - DATABASE_URL=postgresql://usuario:senha@db:5432/fastapi_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
